//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmahLogAnalyzer.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElmahLogAnalyzer.Core.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [CookieValues](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ///	[Name][nvarchar](4000) NULL,
        ///	[Value] [nvarchar](4000) NULL,
        ///	[ErrorLogId] [uniqueidentifier] NOT NULL
        ///).
        /// </summary>
        internal static string SqlCeDatabaseSchemaCookieValuesTable {
            get {
                return ResourceManager.GetString("SqlCeDatabaseSchemaCookieValuesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [ErrorLogs](
        ///	[ErrorId] [uniqueidentifier]  PRIMARY KEY NOT NULL,
        ///	[Host] [nvarchar](4000) NULL,
        ///	[Type] [nvarchar](4000) NULL,
        ///	[Message] [nvarchar](4000) NULL,
        ///	[Source] [nvarchar](4000) NULL,
        ///	[Details] [ntext] NULL,
        ///	[Time] [datetime] NULL,
        ///	[StatusCode] [nvarchar](50) NULL,
        ///	[User] [nvarchar](256) NULL,
        ///	[Url] [nvarchar](4000) NULL)
        ///.
        /// </summary>
        internal static string SqlCeDatabaseSchemaErrorLogsTable {
            get {
                return ResourceManager.GetString("SqlCeDatabaseSchemaErrorLogsTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [FormValues](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ///	[Name][nvarchar](4000) NULL,
        ///	[Value] [nvarchar](4000) NULL,
        ///	[ErrorLogId] [uniqueidentifier] NOT NULL
        ///).
        /// </summary>
        internal static string SqlCeDatabaseSchemaFormValuesTable {
            get {
                return ResourceManager.GetString("SqlCeDatabaseSchemaFormValuesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [QuerystringValues](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ///	[Name][nvarchar](4000) NULL,
        ///	[Value] [nvarchar](4000) NULL,
        ///	[ErrorLogId] [uniqueidentifier] NOT NULL
        ///).
        /// </summary>
        internal static string SqlCeDatabaseSchemaQuerystringValuesTable {
            get {
                return ResourceManager.GetString("SqlCeDatabaseSchemaQuerystringValuesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [ServerVariables](
        ///	[Id] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ///	[Name][nvarchar](4000) NULL,
        ///	[Value] [nvarchar](4000) NULL,
        ///	[ErrorLogId] [uniqueidentifier] NOT NULL
        ///).
        /// </summary>
        internal static string SqlCeDatabaseSchemaServerVariablesTable {
            get {
                return ResourceManager.GetString("SqlCeDatabaseSchemaServerVariablesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;@MESSAGE@&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		body
        ///		{
        ///			font-family: &quot;Verdana&quot;;
        ///			font-weight: normal;
        ///			font-size: .7em;
        ///			color: black;
        ///		}
        ///		p
        ///		{
        ///			font-family: &quot;Verdana&quot;;
        ///			font-weight: normal;
        ///			color: black;
        ///			margin-top: -5px;
        ///		}
        ///		b
        ///		{
        ///			font-family: &quot;Verdana&quot;;
        ///			font-weight: bold;
        ///			color: black;
        ///			margin-top: -5px;
        ///		}
        ///		h1
        ///		{
        ///			font-family: &quot;Verdana&quot;;
        ///			font-weight:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YellowScreenOfDeath {
            get {
                return ResourceManager.GetString("YellowScreenOfDeath", resourceCulture);
            }
        }
    }
}
